import { State } from "../types";
const acceptButton = require('../../assets/images/accept-button.png');
const activeCurrent = require('../../assets/images/active-current.png');
const activeDeferrer = require('../../assets/images/active-deferrer.png');
const activeList = require('../../assets/images/active-list.png');
const activeShare = require('../../assets/images/active-share.png');
const backButton = require('../../assets/images/back-button.png');
const checkbox = require('../../assets/images/checkbox.png');
const city1 = require('../../assets/images/city-1.png');
const city2 = require('../../assets/images/city-2.png');
const cityNote = require('../../assets/images/city-note.png');
const deferrerBg = require('../../assets/images/deferrer-bg.png');
const deferrerButton = require('../../assets/images/deferrer-button.png');
const doneButton = require('../../assets/images/done-button.png');
const deferrerEmpty = require('../../assets/images/deferrer-empty.png');
const deferrerTutorial = require('../../assets/images/deferrer-tutorial.png');
const disableCurrent = require('../../assets/images/disable-current.png');
const disableDeferrer = require('../../assets/images/disable-deferrer.png');
const disableList = require('../../assets/images/disable-list.png');
const doneListBg = require('../../assets/images/done-list-bg.png');
const emptyListNote = require('../../assets/images/empty-list-note.png');
const greenSquare = require('../../assets/images/green-square.png');
const listBg = require('../../assets/images/list-bg.png');
const navBg = require('../../assets/images/nav-bg.png');
const noButton = require('../../assets/images/no-button.png');
const yesButton = require('../../assets/images/yes-button.png');
const pinkSquare = require('../../assets/images/pink-square.png');
const startButton = require('../../assets/images/start-button.png');
const storyButton = require('../../assets/images/story-button.png');
const taskGreen = require('../../assets/images/task-green.png');
const taskPink = require('../../assets/images/task-pink.png');
const tutorial1 = require('../../assets/images/tutorial-1.png');
const tutorial2 = require('../../assets/images/tutorial-2.png');
const tutorial3 = require('../../assets/images/tutorial-3.png');
const blackPixel = require('../../assets/images/black-pixel.png');
const taskDeferrer = require('../../assets/images/task-deferrer.png');
const taskDone = require('../../assets/images/task-done.png');
const artkvartal = require('../../assets/images/backgrounds/artkvartal-min.png');
const attraction = require('../../assets/images/backgrounds/attraction-min.png');
const beach = require('../../assets/images/backgrounds/beach-min.png');
const bed = require('../../assets/images/backgrounds/bed-min.png');
const bookcoworking = require('../../assets/images/backgrounds/bookcoworking-min.png');
const bookpark = require('../../assets/images/backgrounds/bookpark-min.png');
const bridge = require('../../assets/images/backgrounds/bridge-min.png');
const brunch = require('../../assets/images/backgrounds/brunch-min.png');
const bubbles = require('../../assets/images/backgrounds/bubbles-min.png');
const bukhta = require('../../assets/images/backgrounds/bukhta-min.png');
const bukhtawalk = require('../../assets/images/backgrounds/bukhtawalk-min.png');
const buterbrodik = require('../../assets/images/backgrounds/buterbrodik-min.png');
const chackchack = require('../../assets/images/backgrounds/chackchack-min.png');
const chaynaya = require('../../assets/images/backgrounds/chaynaya-min.png');
const chernoyeozero = require('../../assets/images/backgrounds/chernoyeozero-min.png');
const cherry = require('../../assets/images/backgrounds/cherry-min.png');
const children = require('../../assets/images/backgrounds/children-min.png');
const chkalov = require('../../assets/images/backgrounds/chkalov-min.png');
const clay = require('../../assets/images/backgrounds/clay-min.png');
const cleaning = require('../../assets/images/backgrounds/cleaning-min.png');
const cocktail = require('../../assets/images/backgrounds/cocktail-min.png');
const cottoncandy = require('../../assets/images/backgrounds/cottoncandy-min.png');
const coworking = require('../../assets/images/backgrounds/coworking-min.png');
const djset = require('../../assets/images/backgrounds/djset-min.png');
const echpochmak = require('../../assets/images/backgrounds/echpochmak-min.png');
const fire = require('../../assets/images/backgrounds/fire-min.png');
const fruitsalad = require('../../assets/images/backgrounds/fruitsalad-min.png');
const gallery = require('../../assets/images/backgrounds/gallery-min.png');
const giraffe = require('../../assets/images/backgrounds/giraffe-min.png');
const goldfish = require('../../assets/images/backgrounds/goldfish-min.png');
const golubi = require('../../assets/images/backgrounds/golubi-min.png');
const interior = require('../../assets/images/backgrounds/interior-min.png');
const jump = require('../../assets/images/backgrounds/jump-min.png');
const jungle = require('../../assets/images/backgrounds/jungle-min.png');
const kanatka = require('../../assets/images/backgrounds/kanatka-min.png');
const kart = require('../../assets/images/backgrounds/kart-min.png');
const kazanwalk = require('../../assets/images/backgrounds/kazanwalk-min.png');
const kinoparkovka = require('../../assets/images/backgrounds/kinoparkovka-min.png');
const kinoparkovka1 = require('../../assets/images/backgrounds/kinoparkovka1-min.png');
const kotocafe = require('../../assets/images/backgrounds/kotocafe-min.png');
const krugobaikal = require('../../assets/images/backgrounds/krugobaikal-min.png');
const lectority = require('../../assets/images/backgrounds/lectority-min.png');
const literaturegirl = require('../../assets/images/backgrounds/literaturegirl-min.png');
const literaturestairs = require('../../assets/images/backgrounds/literaturestairs-min.png');
const mayak = require('../../assets/images/backgrounds/mayak-min.png');
const mystic = require('../../assets/images/backgrounds/mystic-min.png');
const neobichnoezdanie = require('../../assets/images/backgrounds/neobichnoezdanie-min.png');
const nizhniyyoga = require('../../assets/images/backgrounds/nizhniyyoga-min.png');
const onlinepark = require('../../assets/images/backgrounds/onlinepark-min.png');
const parkrun = require('../../assets/images/backgrounds/parkrun-min.png');
const partyhome = require('../../assets/images/backgrounds/partyhome-min.png');
const peski = require('../../assets/images/backgrounds/peski-min.png');
const photowalk = require('../../assets/images/backgrounds/photowalk-min.png');
const piknik = require('../../assets/images/backgrounds/piknik-min.png');
const pinkmovie = require('../../assets/images/backgrounds/pinkmovie-min.png');
const pishka = require('../../assets/images/backgrounds/pishka-min.png');
const pizza = require('../../assets/images/backgrounds/pizza-min.png');
const planetariy = require('../../assets/images/backgrounds/planetariy-min.png');
const poetry = require('../../assets/images/backgrounds/poetry-min.png');
const pokhod = require('../../assets/images/backgrounds/pokhod-min.png');
const pool = require('../../assets/images/backgrounds/pool-min.png');
const redhat = require('../../assets/images/backgrounds/redhat-min.png');
const rollerskates = require('../../assets/images/backgrounds/rollerskates-min.png');
const running = require('../../assets/images/backgrounds/running-min.png');
const saintp = require('../../assets/images/backgrounds/saintp-min.png');
const saratovphotowalk = require('../../assets/images/backgrounds/saratovphotowalk-min.png');
const saratovyoga = require('../../assets/images/backgrounds/saratovyoga-min.png');
const sdelanovitalii = require('../../assets/images/backgrounds/sdelanovitalii-min.png');
const shashliki = require('../../assets/images/backgrounds/shashliki-min.png');
const skateboard = require('../../assets/images/backgrounds/skateboard-min.png');
const sloboda = require('../../assets/images/backgrounds/sloboda-min.png');
const sosna = require('../../assets/images/backgrounds/sosna-min.png');
const standup = require('../../assets/images/backgrounds/standup-min.png');
const streetsinger = require('../../assets/images/backgrounds/streetsinger-min.png');
const sunrise = require('../../assets/images/backgrounds/sunrise-min.png');
const sunset = require('../../assets/images/backgrounds/sunset-min.png');
const sunsetfriends = require('../../assets/images/backgrounds/sunsetfriends-min.png');
const trenirovka = require('../../assets/images/backgrounds/trenirovka-min.png');
const tsuyvan = require('../../assets/images/backgrounds/tsuyvan-min.png');
const tuvefilm = require('../../assets/images/backgrounds/tuvefilm-min.png');
const veranda = require('../../assets/images/backgrounds/veranda-min.png');
const vgosti = require('../../assets/images/backgrounds/vgosti-min.png');
const vladikphotowalk = require('../../assets/images/backgrounds/vladikphotowalk-min.png');
const volga = require('../../assets/images/backgrounds/volga-min.png');
const wakeboard = require('../../assets/images/backgrounds/wakeboard-min.png');
const walkatnight = require('../../assets/images/backgrounds/walkatnight-min.png');
const walkingmusic = require('../../assets/images/backgrounds/walkingmusic-min.png');
const watermelon = require('../../assets/images/backgrounds/watermelon-min.png');
const wink = require('../../assets/images/backgrounds/wink-min.png');
const yoga2 = require('../../assets/images/backgrounds/yoga2-min.png');
const yogaroof = require('../../assets/images/backgrounds/yogaroof-min.png');
export default class Preload extends Phaser.Scene {
  public state: State;

  constructor() {
    super('Preload');
  }

  public init(state: State) {
    this.state = state;
  }

  public preload(): void {
    this.preloadAssets();
  }

  private preloadAssets(): void {
    this.load.image('accept-button', acceptButton);
    this.load.image('active-current', activeCurrent);
    this.load.image('active-deferrer', activeDeferrer);
    this.load.image('active-list', activeList);
    this.load.image('active-share', activeShare);
    this.load.image('back-button', backButton);
    this.load.image('checkbox', checkbox);
    this.load.image('city-1', city1);
    this.load.image('city-2', city2);
    this.load.image('city-note', cityNote);
    this.load.image('deferrer-bg', deferrerBg);
    this.load.image('deferrer-button', deferrerButton);
    this.load.image('done-button', doneButton);
    this.load.image('deferrer-empty', deferrerEmpty);
    this.load.image('deferrer-tutorial', deferrerTutorial);
    this.load.image('disable-current', disableCurrent);
    this.load.image('disable-deferrer', disableDeferrer);
    this.load.image('disable-list', disableList);
    this.load.image('done-list-bg', doneListBg);
    this.load.image('empty-list-note', emptyListNote);
    this.load.image('green-square', greenSquare);
    this.load.image('list-bg', listBg);
    this.load.image('nav-bg', navBg);
    this.load.image('no-button', noButton);
    this.load.image('yes-button', yesButton);
    this.load.image('pink-square', pinkSquare);
    this.load.image('start-button', startButton);
    this.load.image('story-button', storyButton);
    this.load.image('task-green', taskGreen);
    this.load.image('task-pink', taskPink);
    this.load.image('tutorial-1', tutorial1);
    this.load.image('tutorial-2', tutorial2);
    this.load.image('tutorial-3', tutorial3);
    this.load.image('black-pixel', blackPixel);
    this.load.image('task-deferrer', taskDeferrer);
    this.load.image('task-done', taskDone);
    this.load.image('artkvartal', artkvartal);
    this.load.image('attraction', attraction);
    this.load.image('beach', beach);
    this.load.image('bed', bed);
    this.load.image('bookcoworking', bookcoworking);
    this.load.image('bookpark', bookpark);
    this.load.image('bridge', bridge);
    this.load.image('brunch', brunch);
    this.load.image('bubbles', bubbles);
    this.load.image('bukhta', bukhta);
    this.load.image('bukhtawalk', bukhtawalk);
    this.load.image('buterbrodik', buterbrodik);
    this.load.image('chackchack', chackchack);
    this.load.image('chaynaya', chaynaya);
    this.load.image('chernoyeozero', chernoyeozero);
    this.load.image('cherry', cherry);
    this.load.image('children', children);
    this.load.image('chkalov', chkalov);
    this.load.image('clay', clay);
    this.load.image('cleaning', cleaning);
    this.load.image('cocktail', cocktail);
    this.load.image('cottoncandy', cottoncandy);
    this.load.image('coworking', coworking);
    this.load.image('djset', djset);
    this.load.image('echpochmak', echpochmak);
    this.load.image('fire', fire);
    this.load.image('fruitsalad', fruitsalad);
    this.load.image('gallery', gallery);
    this.load.image('giraffe', giraffe);
    this.load.image('goldfish', goldfish);
    this.load.image('golubi', golubi);
    this.load.image('interior', interior);
    this.load.image('jump', jump);
    this.load.image('jungle', jungle);
    this.load.image('kanatka', kanatka);
    this.load.image('kart', kart);
    this.load.image('kazanwalk', kazanwalk);
    this.load.image('kinoparkovka', kinoparkovka);
    this.load.image('kinoparkovka1', kinoparkovka1);
    this.load.image('kotocafe', kotocafe);
    this.load.image('krugobaikal', krugobaikal);
    this.load.image('lectority', lectority);
    this.load.image('literaturegirl', literaturegirl);
    this.load.image('literaturestairs', literaturestairs);
    this.load.image('mayak', mayak);
    this.load.image('mystic', mystic);
    this.load.image('neobichnoezdanie', neobichnoezdanie);
    this.load.image('nizhniyyoga', nizhniyyoga);
    this.load.image('onlinepark', onlinepark);
    this.load.image('parkrun', parkrun);
    this.load.image('partyhome', partyhome);
    this.load.image('peski', peski);
    this.load.image('photowalk', photowalk);
    this.load.image('piknik', piknik);
    this.load.image('pinkmovie', pinkmovie);
    this.load.image('pishka', pishka);
    this.load.image('pizza', pizza);
    this.load.image('planetariy', planetariy);
    this.load.image('poetry', poetry);
    this.load.image('pokhod', pokhod);
    this.load.image('pool', pool);
    this.load.image('redhat', redhat);
    this.load.image('rollerskates', rollerskates);
    this.load.image('running', running);
    this.load.image('saintp', saintp);
    this.load.image('saratovphotowalk', saratovphotowalk);
    this.load.image('saratovyoga', saratovyoga);
    this.load.image('sdelanovitalii', sdelanovitalii);
    this.load.image('shashliki', shashliki);
    this.load.image('skateboard', skateboard);
    this.load.image('sloboda', sloboda);
    this.load.image('sosna', sosna);
    this.load.image('standup', standup);
    this.load.image('streetsinger', streetsinger);
    this.load.image('sunrise', sunrise);
    this.load.image('sunset', sunset);
    this.load.image('sunsetfriends', sunsetfriends);
    this.load.image('trenirovka', trenirovka);
    this.load.image('tsuyvan', tsuyvan);
    this.load.image('tuvefilm', tuvefilm);
    this.load.image('veranda', veranda);
    this.load.image('vgosti', vgosti);
    this.load.image('vladikphotowalk', vladikphotowalk);
    this.load.image('volga', volga);
    this.load.image('wakeboard', wakeboard);
    this.load.image('walkatnight', walkatnight);
    this.load.image('walkingmusic', walkingmusic);
    this.load.image('watermelon', watermelon);
    this.load.image('wink', wink);
    this.load.image('yoga2', yoga2);
    this.load.image('yogaroof', yogaroof);
  }

  public create(): void {
    this.scene.stop();
    this.scene.start('Start', this.state);
  }
};
